matter-labs/zksync-web-era-docs

docs/api/hardhat/getting-started.md
docs/dev/guide/hello-world.md

1. Fixes small typo ("Prerequisities" -> "Prerequisites")
2. Includes Prerequisites section in `hello-world.md`
3. ~~Adds some extra info saying that Docker must be running during compilation~~

misc(hello-world/getting-started): add prerequisites to hello-world and include some extra helper info

---

docs/dev/zksync-v2/contracts.md
docs/dev/zksync-v2/fee-model.md

there is a duplicated why in this sentense.

remove duplicated why

---

docs/api/js/contracts.md
docs/api/js/front-end.md

This PR fixes a couple of broken links that point to the zkSync features page.

Fix broken link to features page

---

docs/dev/guide/hello-world.md

Updated Hello World tutorial with a warning tip and a compiler version tag

Fix version

---

docs/dev/zksync-v2/system-contracts.md

System contracts: update commit hashes

---

docs/dev/tutorials/README.md

Just fixing links in the Tutorials index page

fix links in tutorials index page

---

docs/dev/tutorials/custom-aa-tutorial.md

There is a missing ")" in the Factory contract.
Also, removed the factory contract address in the code sample and replaced with "<YOUR_FACTORY_ADDRESS>" to avoid confusion.

fix Factory contract

---

docs/dev/tutorials/custom-paymaster-tutorial.md

Identified a few common errors with @StanislavBreadless and added them to the tutorial for reference.
Also increased the amount of ETH we send to the paymaster after it's deployed to avoid issues.
In addition, removes warning on top.

Adds common errors

---

docs/dev/tutorials/custom-paymaster-tutorial.md

Includes fix to calculate the gas fee for the transaction sent to the paymaster.
Improves explanation of what's being built in this tutorial.

Fix/DOC-62 - Paymaster fee calculation

---

docs/.vuepress/config.js

moves l1-l2 to building on zk

---

docs/dev/tutorials/cross-chain-tutorial.md

Calculate the needed gas amount to avoid insufficient balance error on deployment

change funds amount on deployment

---

docs/dev/developer-guides/hello-world.md
docs/dev/fundamentals/testnet.md

Added a link to block explorer and specified that users can add a network manually.

fix: Updated Metamask page

---

docs/.vuepress/config.js
package.json
yarn.lock

Added the back top top button to scroll back to the top if the page is at the bottom.

Added back to top button

---

docs/dev/developer-guides/transactions/blocks.md

I updated the meaning of timestamp in the block docs.

Rephrased sentence

---

docs/dev/developer-guides/hello-world.md

##Description
Remove deprecated settings in the quickstart guide.

Remove deprecated settings

---

docs/dev/developer-guides/hello-world.md

Moved the import statement in the quickstart section up and fix grammatical errors in the same file.

Updated statement

---

docs/.vuepress/theme/components/Home.vue
docs/dev/developer-guides/hello-world.md

Reverts matter-labs/zksync-web-v2-docs#164

revert merge

---

docs/dev/developer-guides/aa.md
docs/dev/developer-guides/hello-world.md
docs/dev/tutorials/custom-paymaster-tutorial.md

Improves explanation of innerInput param for approval based paymasters.
Adds comments in code samples.

improves explanation of innerInput

---

docs/api/hardhat/testing.md
docs/contact.md
docs/dev/fundamentals/testnet.md
docs/dev/troubleshooting/docs-contribution/docs.md
docs/dev/troubleshooting/important-links.md
docs/dev/troubleshooting/status.md
docs/dev/tutorials/README.md
docs/dev/tutorials/custom-paymaster-tutorial.md

Replaced old Discord Link with new link.

Update discord invite link

---

docs/dev/fundamentals/faq.md
docs/dev/fundamentals/testnet.md
docs/dev/troubleshooting/important-links.md

Updated network details info across all affected pages.

Updated network details info

---

docs/dev/fundamentals/faq.md

Added a response to smart contract storage limit.

Added response to contract storage limit

---

docs/dev/developer-guides/bridging/l1-l2.md

Added a tip to L1 -> L2 section, to show the successful and failed responses of what L1 -> L2 message produces.

Added tip to L1 -> L2 section

---

docs/api/tools/block-explorer/contract-verification.md

Updated content on contract verification page

Updated content on contract verification page

---

docs/.vuepress/config.js
package.json
yarn.lock

Fix the search feature with vuepress-plugin-flexsearch.

Fix the search feature

---

docs/dev/fundamentals/faq.md

faucet link by alchemy which actually has some gETH

added a faucet link

---

docs/dev/fundamentals/faq.md

Documented details on our  block gas limit on zkSync 2.0

Add faq for block gas limit

---

docs/api/hardhat/plugins.md
docs/api/hardhat/testing.md
docs/dev/developer-guides/hello-world.md
docs/dev/tutorials/cross-chain-tutorial.md
docs/dev/tutorials/custom-aa-tutorial.md
docs/dev/tutorials/custom-paymaster-tutorial.md

Updates tutorials with new hardhat config for zksync-deploy v0.6.x
To be merged together with #211

new API for zksync-deploy v0.6

---

docs/api/README.md
docs/api/api.md
docs/api/go/getting-started.md
docs/api/hardhat/compiling-libraries.md
docs/api/hardhat/getting-started.md
docs/api/hardhat/plugins.md
docs/api/hardhat/testing.md
docs/api/java/getting-started.md
docs/api/js/accounts-l1-l2.md
docs/api/js/accounts.md
docs/api/js/features.md
docs/api/js/front-end.md
docs/api/js/getting-started.md
docs/api/js/providers.md
docs/api/js/utils.md
docs/api/python/getting-started.md
docs/api/tools/block-explorer/block-view.md
docs/api/tools/block-explorer/contract-verification.md
docs/api/tools/block-explorer/intro.md
docs/api/tools/block-explorer/search.md
docs/api/tools/block-explorer/zkevm.md
docs/api/tools/zksync-cli/README.md

Added TOC to the tools/SDK section of the docs.

Add TOC to tools/sdk section

---

docs/.vuepress/config.js
package.json
yarn.lock

Replace the previous search implementation with the Algolia search.

Add algolia support

---

docs/dev/developer-guides/hello-world.md

removed unnecessary enumeration
fixed errored enumeration

enumeration + typos

---

docs/dev/troubleshooting/README.md

reordered + actualized naming with regards to current structure

actualization

---

docs/dev/troubleshooting/docs-contribution/docs.md

added zkSync twitter hyperlink
removed unnecessary comma

some fixes/adds

---

docs/api/hardhat/getting-started.md
docs/api/hardhat/plugins.md

updated hardhat config, removed the docker part.

updated hardhat config

---

docs/dev/README.md

Added all SDK's, zkSync CLI, hardhat plugins to the overview page.

added tool/sdk to overview page

---

docs/api/js/providers.md

Variables actualized

---

README.md

Just adds information on how to add new tutorials in the README file

adds info how-to new tutorials

---

docs/api/api.md
docs/api/go/getting-started.md
docs/api/java/getting-started.md
docs/api/js/accounts-l1-l2.md
docs/api/js/getting-started.md
docs/api/python/getting-started.md
docs/api/swift/getting-started.md
docs/dev/developer-guides/aa.md
docs/dev/developer-guides/bridging/l1-l2.md
docs/dev/developer-guides/bridging/l2-l1.md
docs/dev/developer-guides/hello-world.md
docs/dev/developer-guides/transactions/fee-model.md

Reverts matter-labs/zksync-web-v2-docs#274

Revert "Renaming "ergs" to gas in the docs."

---

docs/.vuepress/config.js
docs/dev/developer-guides/building-on-zksync/fair-onboarding-alpha.md

Adds M5 page: https://aqwzx-zksync-v2-docs--pr289-feat-fair-onboarding-4aqjwfw9.web.app/dev/developer-guides/building-on-zksync/fair-onboarding-alpha.html

adds M5 page

---

docs/.vuepress/styles/index.scss

Disable hero-img link on the homepage.

disable hero-img link

---

docs/dev/building-on-zksync/fair-onboarding-alpha.md
docs/dev/troubleshooting/changelog.md
firebase.json

Fixes broken links in Fair onboarding page
Adds new changelog entry

Links and changelog

---

docs/api/hardhat/getting-started.md

typo fix in solidity snippet

---

docs/dev/developer-guides/transactions/transactions.md

I believe it should be a payment "from" the author, rather than "to" the author. 
Hope that helps :)

Gas payment from the author

---

docs/dev/building-on-zksync/hello-world.md

This PR proposes to move private key variable to environment variables in the hello-world.md tutorial

Update `deploy.ts` in hello-world.md: move privKey to environment variables

---

docs/dev/tutorials/aa-daily-spend-limit.md
docs/dev/tutorials/custom-aa-tutorial.md

Adds the information about contracts using SystemContractsCaller, which requires compilation with `isSystem` flag, and the hardhat config file.
Updated code snippet AA Daily spend limit account tutorial.

Update AA Daily spend limit account tutorial 

---

docs/README.md

[DOC 218](https://linear.app/matterlabs/issue/DOC-218/httpsmostmatter-labsiomatterlabsplwpnu3xz4dpfutkcdhcj55mencw)
- Fixing urgent incorrect text on front page.
- Some minor text improvements while I was there.

Fixing text on frontpage

---

docs/api/api.md
docs/api/js/providers.md

fix returned tokens format

---

docs/dev/compiler-toolchain/overview.md
docs/dev/compiler-toolchain/solidity.md

Properly defined headers and converted lists to headers in the compiler toolchain section.

Properly defined headers in the compiler toolchain section

---

docs/dev/README.md
docs/dev/developer-guides/bridging/bridging-asset.md

Wrote a paragraph on how to add tokens to the bridge.

Add token to bridge

---

docs/.vuepress/sidebar/en.ts

* Moving the out-of-date API documentation down temporarily.

Reorder menus on API page

---

docs/.vuepress/config.ts

updated pwa config

---

docs/dev/building-on-zksync/hello-world.md

Unmerged change found its way in to the doc.

Remove merge issue

---

docs/dev/developer-guides/bridging/l1-l2.md

- [DOC-140](https://linear.app/matterlabs/issue/DOC-140/l1-l2-comms-ergs-gas-price) is done already with previous work.
- Looking through, I made a minor update to a warning box re: ergs.

DOC-140 minor update

---

docs/contact.md

Updated the contact page from Estevan's suggestion here - https://linear.app/matterlabs/issue/DOC-274/remove-hellomatter-labsio

updated contact page

---

docs/dev/developer-guides/bridging/bridging-asset.md

Added a link to the withdrawal method in this [section]( https://era.zksync.io/docs/dev/developer-guides/bridging/bridging-asset.html#withdrawals-to-l1).

Added link to withdraw method

---

docs/dev/developer-guides/transactions/transactions.md

Removed repetition in the transaction types section.

Removed repetition

---

docs/api/js/getting-started.md
docs/dev/developer-guides/bridging/bridging-asset.md
docs/dev/developer-guides/bridging/l1-l2.md
docs/dev/developer-guides/bridging/l2-l1.md
docs/dev/troubleshooting/changelog.md

Added bridging script to deposit ETH and ERC20 tokens to L2.

Added bridging script 

---

docs/dev/developer-guides/aa.md

Fix to match methods in the docs with the methods defined in the [IAccount](https://github.com/matter-labs/v2-testnet-contracts/blob/main/l2/system-contracts/interfaces/IAccount.sol) and [IPaymaster](https://github.com/matter-labs/v2-testnet-contracts/blob/main/l2/system-contracts/interfaces/IPaymaster.sol) interfaces

fixes to match interfaces methods

---

docs/dev/tutorials/cross-chain-tutorial.md

- Tutorial now running on 1.3.10 compiler. 
- All script issues fixed.
- Code matching the repo: https://github.com/matter-labs/cross-chain-tutorial/pull/16/files -> @uF4No

Cross chain tutorial: new code, compiler version update, and script fix

---

docs/.vuepress/styles/index.scss

Made paragraph unjustified, and removed hyphens.

Removed hyphens and made paragraph unjustified

---

docs/dev/tutorials/custom-paymaster-tutorial.md

Updates to match with repo code in [this PR](https://github.com/matter-labs/custom-paymaster-tutorial/pull/12)
Adds some clarifications

Paymaster tutorial: matches with repo code

---

docs/dev/developer-guides/transactions/blocks.md

Added a note on revert blocks.

Add a note on revert blocks

---

docs/api/js/types.md

- Improvements to the JS API docs Types page, renamed Types and interfaces.

Types page improvements/DOC-276

---

docs/.vuepress/sidebar/en.ts
docs/api/hardhat/hardhat-zksync-solc.md
docs/api/hardhat/hardhat-zksync-upgradable.md
docs/api/hardhat/plugins.md
docs/dev/troubleshooting/changelog.md

Adds changelog
Includes #422 (upgradable plugin)
Includes #478 (zksolc metadata)

adds changelog for May

---

docs/dev/building-on-zksync/contracts/differences-with-ethereum.md

Completing: https://linear.app/matterlabs/issue/DOC-297/add-tip-to-differences-with-ethereum-page

Add proxy tip

---

docs/.vuepress/sidebar/en.ts
docs/api/hardhat/other-plugins.md

https://linear.app/matterlabs/issue/DOC-330/put-the-plugins-in-a-submenu

Add plugin submenu

---

docs/dev/building-on-zksync/useful-address.md

Updated the useful address section, with more addresses listed on our block explorer.

update useful addresses

---

docs/.vuepress/components/PageFooter.vue

fixed email link pointing to 404.

fix email link

---

docs/.vuepress/config.ts

Added social share preview link to docs.
Unfortunately, we can't preview on staging, only on prod.

Add social share preview link to docs

---

docs/.vuepress/config.ts

Updated the meta tag so social share images can be previewed.

Updated the meta tag

---

docs/api/api.md

fix broken links

---

docs/.vuepress/styles/index.scss

Remove spaces between h3 and h4

Remove spaces between h3 and h4

---

docs/dev/developer-guides/transactions/transactions.md

Came across this while reading

Small correction in tx finalization

---

docs/dev/developer-guides/videos.md

The first video is important to watch as it summarizes most of the contents of the "Differences with Ethereum" section.
Developers need their attention drawn to this video at least to be aware of the changes in using `create` and `create2`, gas price differences, etc.

Updated videos.md to be more explicit.

---

docs/dev/troubleshooting/faq.md

Error amended

---

docs/dev/developer-guides/aa.md

Fixed smart contract broken link.

Fixed contract broken link

---

docs/.vuepress/sidebar/en.ts
docs/dev/building-on-zksync/hello-world.md
docs/dev/building-on-zksync/rpc.md
docs/dev/developer-guides/finality.md

-> Adding Finality doc to conceptual material.
-> Restructuring conceptual material in preparation for better organization.

Add finality doc

---

docs/dev/tutorials/custom-aa-tutorial.md

Fix typo in AA tutorial comments

---

docs/api/js/paymaster-utils.md
docs/api/js/utils.md
docs/dev/README.md
docs/dev/building-on-zksync/README.md
docs/dev/developer-guides/aa.md

Added tables to utility and paymasters utility page.

Add tables to utility page

---

docs/dev/how-to/estimate-gas.md
docs/dev/how-to/send-transaction-l1-l2.md

Updated links, changed private links to public links.

Updated links

---

docs/dev/tutorials/custom-aa-tutorial.md

https://linear.app/matterlabs/issue/DOC-63/account-abstraction-clarifications
Added useful links to documentation and one comment in code.

DOC-63: Adding clarifications to the AA tutorial

---

docs/dev/tutorials/api3-usd-paymaster-tutorial.md

- Tidied up some of the language.
- A couple of minor clarifications.

Quick proof and test of dAPI3 tutorial

---

docs/reference/troubleshooting/changelog.md

**Changes introduced:**
- Updates changelog to reflect latest changes to HH plugins

chore: update changelog to reference plugin changes

---

docs/dev/README.md
docs/dev/how-to/verify-contracts.md
docs/reference/troubleshooting/important-links.md

**Changes introduced in this pr:**
- Updates Build page to include "How to verify contracts" 
- Adds developer discussion link

chore: Adds how to verify contracts to build page,  small fixes

---

docs/dev/tutorials/api3-usd-paymaster-tutorial.md

Just a small problem in MyPaymater.sol

Delete duplicated wrong line on MyPaymaster.sol file

---

docs/reference/concepts/aa.md

Changes introduced:
- fixes outdated fn name in aa example

fix: outdated fn name in aa example

---

docs/.vuepress/config.ts

adds html meta tag for ahrefs verification

adds ahrefs verification

---

docs/reference/concepts/bridging-asset.md

* Updates incorrect command in docs
* The command is wrong and users are copying pasting it expecting it to work

chore: fixes incorrect command

---

docs/reference/architecture/differences-with-ethereum.md

* Add Solidity examples for differences from Ethereum
* Fix some namings like zkEVM -> EraVM
* Examples allow better understanding the differences between platforms
* Some namings were outdated

feat: add Solidity examples and make some QoL fixes

---

docs/README.md
docs/dev/building-on-zksync/best-practices.md
docs/reference/architecture/differences-with-ethereum.md
docs/reference/concepts/blocks.md
docs/reference/troubleshooting/changelog.md

* Adds a warning message about the upcoming protocol upgrade
* Heads-up to reach more devs
In preview

Upgrade warning message

---

docs/assets/data/devtools.json
docs/tools/README.md

fix: broken links

---

docs/reference/troubleshooting/faq.md

Add chainstack faucet link

---

docs/dev/building-on-zksync/hello-world.md

Based on the Feedback QA session:
https://www.notion.so/matterlabs/Hello-world-tutorial-QA-feedback-5b8d6c3b214a4db99471c48fbc99d656
Created a PR to fix/inprove spotted version
[***ERROR]*** ❌ - reported 
**We need to use `nvm use —lts` !**
[***ERROR]*** ❌
When the FE part is up and running we have next error while connecting MM:
*For Testnet in MM:*
*For Mainnet in MM:*
We have to mention that is not ready for use and login with MM account. Because here it looks like the connection should be established and ok. And the user might try multiple times to login and receive such errors, with the idea that smth wrong and user can’t proceed further in the tutorial.
[***SUGGESTION]:***💡
Maybe let’s use uppercase to make it clear that we are talking about token names?
[***SUGGESTION]:***💡
Let’s …

qa: feedback session changes for "Hello, world" tutorial

---

docs/dev/tutorials/custom-paymaster-tutorial.md

Fixed typo error
* All the added fixes based on the [Building a custom paymaster - QA feedback](https://www.notion.so/matterlabs/Building-a-custom-paymaster-QA-feedback-08ea3273d2624b76a0bb98145cf11ec2)

qa: feedback session changes for Building a custom paymaster tutorial

---

docs/dev/tutorials/custom-aa-tutorial.md

1) Step #1 - add information what to choose:
2) Step #3: 
```bash
cd ~/custom-aa-tutorial 
```
we have to update just to
3) https://era.zksync.io/docs/dev/tutorials/custom-aa-tutorial.html#account-abstraction
The skeleton code for the contract is given below - *****************************************For what?, no information what to do here.*****************************************

qa: account abstraction multisig 

---

docs/dev/tutorials/api3-usd-paymaster-tutorial.md

* Consolidate same Wallet private key insertaion step from previous PRs

qa: USDC paymaster tutorial with API3 dAPIs

---

cspell-zksync.txt
docs/reference/architecture/differences-with-ethereum.md

DOC update for `PREVRANDAO`

---

docs/dev/community-tutorials/the-graph-tutorial.md
docs/dev/community-tutorials/zksync-cli-quickstart.md

[***SUGGESTION]:***💡
Let’s mention not specific version of Node.js and Yarn, but use instead Node.js LTS and Yarn LTS
1. Create a sample project 
[***ERROR]*** ❌ Change command to: `zksync-cli % zksync-cli create quickstart && cd quickstart`
[[***SUGGESTION](https://github.com/matter-labs/zksync-web-era-docs/compare/***%F0%9F%92%A1)]:***💡 Add “Choose Solidity section

[qa] update for Quickstart with zksync-cli tutorial

---

docs/reference/troubleshooting/audit-bug-bounty.md

Audit doc update

---

docs/assets/data/devtools.json

* Update SubQuery category in Developer Tools
* It's a data indexer

docs: update subquery category

---

docs/api/js/accounts.md

* code formatting for [Wallet](https://era.zksync.io/docs/api/js/accounts.html#wallet) section in Accounts: Overview.
* better formatted code 🤷‍♂️

chore: code formatting

---

cspell-zksync.txt
docs/.vuepress/theme.ts
docs/README.md
docs/dev/building-on-zksync/hello-world.md
docs/dev/tutorials/aa-daily-spend-limit.md
docs/dev/tutorials/api3-usd-paymaster-tutorial.md
docs/dev/tutorials/cross-chain-tutorial.md
docs/dev/tutorials/custom-aa-tutorial.md
docs/reference/troubleshooting/faq.md
docs/tools/hardhat/getting-started.md
docs/tools/hardhat/hardhat-zksync-deploy.md
docs/tools/hardhat/hardhat-zksync-vyper.md
docs/tools/hardhat/migrating-to-zksync.md

* Replaced all the goerli.portal.zksync.io/faucet and portal.zksync.io/ mentions
* Updated third party faucets list

chore: update pages with third party faucets and removed zksync portal and faucets mentions

---

docs/dev/building-on-zksync/best-practices.md
docs/dev/tutorials/gated-nft-paymaster-tutorial.md

* Grammar fixes reported from the community
* for proper grammar
Just updated 2 words 

Doc grammar fixes

---

docs/api/go/README.md
docs/api/go/accounts.md

* Updated examples for `Wallete.requestExecute` method
* This version is more clear for reader.

fix(go-sdk): resolved errors in examples for `Wallet.requestExecute` method

---

docs/.vuepress/sidebar/en.ts
docs/reference/README.md
docs/reference/concepts/validiums.md

* Adds quick summary page relevant to validiums 
* To provide additional clarity in the validium research track

chore: add validium quick summary page (ethglobal track)

---

docs/dev/building-on-zksync/hello-world.md
docs/reference/architecture/differences-with-ethereum.md

Update hello world tutorial instructions.
Hello world tutorial has to be updated to reflect latest template changes.

fix: update hello world tutorial instructions

---

docs/reference/concepts/bridging-asset.md
docs/reference/troubleshooting/faq.md

* Update "add token to bridge" info
* Add token listing FAQ
* Make it clear where Explorer and Bridge takes tokens info from

fix: update tokens listing info

---

docs/tools/zksync-cli/README.md
docs/tools/zksync-cli/examples/contract-interaction.md

* Added info about contract interaction and wallet commands
* Update some of the outdated info
* Make docs up-to-date with latest version of the CLI

fix: update cli docs

---

docs/dev/tutorials/aa-daily-spend-limit.md
docs/dev/tutorials/api3-usd-paymaster-tutorial.md

- More fixes regarding the sepolia migration

Add sepolia migration updates

---

docs/assets/data/devtools.json

* Removed the "soon" for chainlink in the tools

fix(tools): removed soon for chainlink

---

docs/api/api.md
docs/api/js/providers.md
docs/api/js/zksync2-js/providers.md

- Removes mentions of `zks_getConfirmedTokens`.
- This was an internal-only method, it has no usage on mainnet according to our metrics, so it's being removed from the codebase completely.

feat: Remove zks_getConfirmedTokens docs

---

docs/build/api.md

* Added `zks_getProof` info to API
* Method is currently undocumented
* See API page in preview
Unlike other API methods, this one has a lot of info. The "Output" section is slightly different as it includes a description of the returned fields, which I think is required in this case as this method is quite complex.

Adds zks_getProof to API docs

---

.github/workflows/deploy-prod.yml

- Clear CF cache for production documentation
- Cache doesn't cleaned

ci: add step for clear prod cache

---

docs/build/support/faq.md
docs/build/tooling/network-faucets.md

* Add LearnWeb3 Sepolia faucets
* Update FAQ to point to network faucets page
* It's been added for full support and great addition to the page :)
* This will help consolidate the places where we mention network faucets for easier management
* This will replace https://github.com/matter-labs/zksync-web-era-docs/pull/854 created by @haardikk21

chore: add learnweb3 faucet and consolidate mentions of network faucets

---

docs/build/tutorials/smart-contract-development/account-abstraction/daily-spend-limit.md

* Fixes a remaining `ergs` mention in the daily spend limit tutorial
* We changed from ergs to gas months ago
In preview

fix: updates ergs to gas

---

docs/build/support/audit-bug-bounty.md

* Added audits from OZ published recently
* The audits were missing, this is fixed now
Trust me bro /s

Add missing audits from OpenZeppelin

---

docs/build/tutorials/dapp-development/frontend-quickstart-paymaster.md

* Updated `yarn serve` command to `yarn dev` since `yarn serve` causes an error

fix: fixed yarn command

---

docs/build/tooling/hardhat/hardhat-zksync-upgradable.md

* `chalk.green` causes an error when running script - removed it
* Causing failures as `chalk` not necessarily installed

fix: update beacon proxy file

---

docs/build/test-and-debug/hardhat.md
docs/build/tutorials/how-to/send-transaction-l1-l2.md
docs/build/tutorials/smart-contract-development/paymasters/allowlist.md
docs/build/tutorials/smart-contract-development/paymasters/erc20fixed.md
docs/build/tutorials/smart-contract-development/paymasters/gasless.md
docs/build/tutorials/smart-contract-development/paymasters/timebased.md
docs/build/tutorials/tooling-guides/api3.md
docs/build/tutorials/tooling-guides/dia.md
docs/zk-stack/running-a-hyperchain/locally.md
docs/zk-stack/running-a-hyperchain/using-hyperchain.md

* Updated cli create project command to `npx zksync-cli create [options]`
* Removed obsolete @latest tag after `zksync-cli`

fix: updated cli create project command

---

docs/build/quick-start/add-zksync-to-metamask.md

* Fixed a bug network name not display properly
* for user to check easily and comfortably

fix: network name not display properly

---

docs/build/tutorials/smart-contract-development/cross-chain-tutorial.md

* Updates to reflect latest dep changes from HH 
* Updates to make use of ethers v6
* Fixes CLI commands
* Should always use latest and greatest
* Issue with CLI command 

fix: Update cross-chain tutorial to make use of latest deps and ethers v6 

---

docs/build/tooling/hardhat/hardhat-zksync-solc.md

* Adds missing commas in config example
* It allows to copy/paste the config from the example

chore(hardhat-zksync-solc.md): makes it easier to copy-paste

---

docs/build/developer-reference/contract-deployment.md

Just making more clear what is this sectino about

feat: improving title

---

docs/build/quick-start/useful-address.md

Protocol v21 upgrade required a new timelock contract

feat: updating validator timelock addresses

---

docs/zk-stack/concepts/data-availability/overview.md

fix: changing link to public updated repos

---

docs/.vuepress/components/NavBar.vue
docs/.vuepress/sidebar/en.ts
docs/.vuepress/styles/index.scss
docs/.vuepress/theme.ts
docs/build/quick-start/useful-address.md
docs/build/sdks/go/accounts.md
docs/build/sdks/go/clients.md
docs/build/sdks/java/getting-started.md
docs/build/sdks/js/providers.md
docs/build/sdks/js/types.md
docs/build/sdks/js/zksync-ethers/providers.md
docs/build/sdks/js/zksync-ethers/types.md
docs/build/test-and-debug/era-test-node.md
docs/build/tooling/oracles.md
docs/build/tutorials/dapp-development/gated-nft-paymaster-tutorial.md
docs/build/tutorials/how-to/deposit-erc-20-to-l2.md
docs/build/tutorials/how-to/deposit-eth-to-l2.md
docs/build/tutorials/how-to/withdraw-erc-20-to-l1.md
docs/build/tutorials/how-to/withdraw-eth-to-l1.md
docs/build/tutorials/smart-contract-development/cross-chain-tutorial.md
docs/build/tutorials/smart-contract-development/paymasters/custom-paymaster-tutorial.md
docs/zk-stack/running-a-hyperchain/locally.md

* Removing mentions of Goerli
* Adding banner about its deprecation
* Because Goerli testnet will be turned off

feat: adding banner and removing most of sepolia mentions

---

docs/.vuepress/styles/index.scss

fix ui on mobile for tem banner

fix: responsiveness

---

docs/build/sdks/js/accounts.md
docs/build/sdks/js/zksync-ethers/accounts.md
docs/build/sdks/js/zksync-ethers/providers.md
docs/build/sdks/js/zksync-ethers/utils.md

* Fix the errors in documentation.

fix(js-sdk): fix erors in documentation

---

docs/build/sdks/go/accounts.md
docs/build/sdks/go/clients.md
docs/build/sdks/go/contracts.md
docs/build/sdks/go/getting-started.md
docs/build/sdks/go/types/types.md
docs/build/sdks/go/utils.md

* Align documentation with `v0.4.0` release.

Go SDK: update for `v0.4.0` release

---

README.md

* Updated `yarn add` to `yarn`
* More clear this way

fix: change readme from yarn add to just yarn

---

docs/build/tooling/foundry/getting-started.md

* Update installation content to reflect `main` branch usage
* The default branch for development during v2 is `dev`, we want to avoid confusion until its ready

chore: update installation for foundry to target `main` branch
