- docs/api/api.md
- docs/api/hardhat/getting-started.md
- docs/api/js/accounts-l1-l2.md
- docs/api/js/accounts.md
- docs/api/js/features.md
- docs/api/js/getting-started.md
- docs/api/js/providers.md
- docs/dev/guide/hello-world.md
- docs/dev/guide/l1-l2.md
I noticed when going through the docs that the USDC address was still pointing to the [rinkeby version](https://rinkeby.etherscan.io/address/0xeb8f08a975ab53e34d8a0330e0d34de942c95926). This will update it everywhere found in the docs to the [goerli version](https://goerli.etherscan.io/address/0xd35cceead182dcee0f148ebac9447da2c4d449c4)
> Update usdc token address to goerli address

- docs/api/hardhat/compiling-libraries.md
- docs/api/hardhat/getting-started.md
- docs/dev/guide/cross-chain-tutorial.md
- docs/dev/guide/hello-world.md
Right now, if anyone uses the default setup shown in the tutorials within the documentation, they will be using a heavily throttled default API key:
I don't believe it is clear or obvious how to avoid this, so I think adding these comments from this PR into the example code will make it much easier for developers to avoid running into this throttling (by pointing out where their own RPC address can be provided).
> misc(config/zkSyncDeploy/ethNetwork): shows where RPC can be provided

- docs/api/js/getting-started.md
- docs/dev/testnet/known-issues.md
> Minor fixes

- docs/api/hardhat/testing.md
[Accompanying PR to the tutorials code repo](https://github.com/matter-labs/tutorial-examples/pull/23).
Tutorial is mostly up-to-date as it is, so I just removed warnings and added a note about ERC-20 tokens no longer being shipped.
> Update the local node tutorial

- docs/api/hardhat/compiling-libraries.md
- docs/api/hardhat/getting-started.md
- docs/dev/developer-guides/hello-world.md
- docs/dev/tutorials/cross-chain-tutorial.md
**Don't merge yet**
Only merge this when a docker image `matterlabs/zksolc:v1.2.0` is published.
This makes tutorials up to date with the updated testnet (regenesis expected Mon 10.10.2022).
Don't forget to publish the 0.11.0 `zksync-web3` as well.
> Update compiler tag

- docs/dev/tutorials/custom-aa-tutorial.md
Fixes typo in contract and increase amount of ETH sent to multisig wallet to 0.003ETH to make sure there's enough to cover transactions fees. Also mentions this as a possible error.
In addition, fixes broken link and removes warning on top.
Same fixes for the code repo incoming.
> Fixes account abstraction tutorial

- docs/dev/developer-guides/hello-world.md
- docs/dev/developer-guides/transactions/aa.md
- docs/dev/fundamentals/testnet.md
- docs/dev/tutorials/README.md
- docs/dev/tutorials/cross-chain-tutorial.md
- docs/dev/tutorials/custom-aa-tutorial.md
- docs/dev/tutorials/custom-paymaster-tutorial.md
Fixes typos found by Anthony.
Changes all references of "Hello world" to Quickstart tutorial
> Fix/DOC-57: typos and minor improvements

- docs/.vuepress/config.js
- docs/api/hardhat/README.md
- docs/api/hardhat/compiling-libraries.md
- docs/api/hardhat/getting-started.md
- docs/api/hardhat/plugins.md
- docs/api/hardhat/testing.md
- docs/dev/tutorials/README.md
- docs/dev/tutorials/custom-aa-tutorial.md
Renames "Reference" page to "Plugins".
Improves description of configuration fields like `compilerSource`.
Typos.
Fixes typo in AA tutorial
Adds more content in tutorials index page
> Plugins page and other fixes

- docs/contact.md
- docs/dev/troubleshooting/docs-contribution/docs.md
- docs/dev/troubleshooting/important-links.md
Community Forum is no longer working so removed the link in the docs.
> fix: Remove forum link

- docs/api/hardhat/getting-started.md
Updated the documentation to be compatible with Yarn v3:
* added missing dependencies to the install command
* added a tip for Yarn to work as expected in editors
* fixed the `hardhat.config.ts` file example
> fix(hardhat/getting-started): Yarn v3 updates

- docs/dev/developer-guides/bridging/l2-l1.md
Follow-up on the discord thread https://discord.com/channels/722409280497516566/1064852922611011624/1065592019398967326
Summary of changes:
- ``l2Receipt.hash``->`` l2Receipt.transactionHash``
- ``trx.transactionIndex -> l1BatchTxIndex``
- ``l1BatchNumber`` and ``l1BatchTxIndex`` can be retrieved from the L2 Tx receipt after the Tx is finalized
> Fix the "Proving the inclusion of the message into the L2 block" e2e example

- docs/api/hardhat/hardhat-zksync-solc.md
- docs/dev/troubleshooting/changelog.md
- docs/dev/tutorials/custom-aa-tutorial.md
Adds information about contracts using `SystemContractsCaller`, which requires compilation with `isSystem` flag.
Adds info about flattening contracts in Changelog
Updates AA tutorial
> info about systemCall and isSystem in compiler AA tutorial

- docs/dev/building-on-zksync/contracts/contracts.md
provided hackernoon link about tx.origin phishing and other vulnerabilities, formatted the same way as the ecrecover usage passage on line 72. We still see tx.origin vulnerabilities in the wild so every little bit of visibility on this issue helps!
also a grammar fix: "we've skip it for now" -> "we've skipped it for now"
> Added context for tx.origin phishing

- docs/dev/troubleshooting/faq.md
Stated why zkSync Era does not prove all batches on testnet on the FAQ page.
> FAQ on why zkSync does not prove all batches on testnet

- docs/api/go/getting-started.md
I was going through the go-sdk docs for zkSync Era, and found out that the import parts of the go scripts could need a change. I saw that some scripts were importing go-ethereum/rpc although it was supposed to import go-ethereum/common. In the general script, rpc is needed, but since the docs were organized according to single functions (deposit, withdraw etc.), not importing the necesssary packages could confuse developers. 
I changed the go-ethereum/rpc imports to go-ethereum/common wherever they were supposed to be imported.
> change go-sdk: go-ethereum/rpc to common

- docs/dev/developer-guides/system-contracts.md
Since you have open sourced the bootloader contract it needs to be updated, some devs or researchers who wants to build on a top of zkSync Era may be confused with this paragraph: "For now, you do not have to know any details about it, but knowing that it exists is important when you develop using the account abstraction feature. You can always assume that the bootloader is not malicious and it is a part of the protocol. In the future, the code of the bootloader will be made public and any changes to it will also mean an upgrade to the protocol." 
It would be better to share the audit and the codebase at your docs. 
[#](https://era.zksync.io/docs/dev/developer-guides/system-contracts.html#protected-access-to-some-of-the-system-contracts)
> Update system-contracts.md - 

- docs/dev/README.md
- docs/dev/compiler-toolchain/overview.md
- docs/dev/developer-guides/bridging/l1-l2.md
- docs/dev/tutorials/custom-aa-tutorial.md
- docs/dev/tutorials/custom-paymaster-tutorial.md
Fix dead links and remove the repetitive section on the overview page.
> Fix dead links

- docs/dev/troubleshooting/withdrawal-delay.md
Changed the header from "Why can't I find my transaction in the block explorer?" to "Why can't I find my withdraw on Etherscan?"
> updated header

- docs/api/hardhat/hardhat-zksync-solc.md
- docs/dev/compiler-toolchain/overview.md
- Added a comment that docker is deprecated and binary should be used in the `compilerSource` param.
- Also wrote a tip that `zksolc <contract>.sol --bin` command is to be used to compile with binaries.
> compile with binaries

- docs/dev/tutorials/cross-chain-tutorial.md
This PR removes the unused Wallet import from the zksync-web3 package in cross-chain-tutorial.md. The import statement for Wallet was found in the following code:
```
import { Contract, Provider, Wallet } from "zksync-web3";
```
However, Wallet is not used anywhere in the codebase. Therefore, it can be safely removed.
> Remove unused 'Wallet ' import

- docs/api/hardhat/getting-started.md
For users to be able to copy paste the code, the comma was needed.
> Missing Comma in ts code of hardhat configs

- docs/api/hardhat/getting-started.md
- docs/api/hardhat/migrating-to-zksync.md
Changes HH quickstart to use CLI
Moves "Multiple targets" section to migration guide.
Adds info for hardhat-deploy in migration guide.
> Hardhat quickstart changes

- docs/dev/developer-guides/bridging/l2-l1.md
- Ticket: https://linear.app/matterlabs/issue/DOC-145/update-l2-l1-page-to-not-use-getmessageproof-but-getlogproof-on-zksync
- Referring to Web3 API docs, I made two changes. Please check @StanislavBreadless / @vladbochok
> Update getMessageProof to getLogProof in L2-L1 doc

- docs/dev/building-on-zksync/contracts/contract-development.md
Minor addition to docs with regards to unsupported Solidity functions.
From ticket here: https://linear.app/matterlabs/issue/DOC-261/document-we-do-not-support-the-following-solidity-methods
> Add unsupported Solidity functions

- docs/dev/building-on-zksync/contracts/contract-development.md
Stated clearly that we support only Vyper `0.3.3`.
> vyper support

- docs/.vuepress/sidebar/en.ts
- docs/api/README.md
- docs/api/js/README.md
- docs/api/js/providers.md
- docs/api/js/types.md
- docs/api/js/utils.md
- docs/dev/developer-guides/bridging/bridging-asset.md
- Added `getL1BatchDetails`
- Some wordage fixes: TS vs JS, function name vs explanation, alpha list
- Copy/paste `Types` code from source ... to be documented properly shortly in DOC-276
- Added Custom Bridge updates from DOC-288 also
> Add getL1BatchDetails, tidy docs a wee bit, update Types, include Custom Bridge updates DOC-288

- firebase.json
Redirected the broken link on Matterlabs website homepage from `/dev/fundamentals/faq.html` to `/dev/troubleshooting/faq.html`.
To test, go to the faq [page](https://aqwzx-zksync-v2-docs--pr457-redirect-link-doc-29-x2nhqtu4.web.app/docs/dev/fundamentals/faq.html), it should redirect you to the [right](https://aqwzx-zksync-v2-docs--pr457-redirect-link-doc-29-x2nhqtu4.web.app/docs/dev/troubleshooting/faq.html) page.
> Added redirect to broken link on website

- firebase.json
Redirected the block section from the [old docs](https://docs-v2-zksync.web.app/dev/developer-guides/transactions/blocks.html#blocks-in-zksync-2-0) to the [new docs](https://era.zksync.io/docs/dev/developer-guides/transactions/blocks.html#blocks-in-zksync-era)
> Redirect block section 

- docs/dev/tutorials/cross-chain-tutorial.md
A couple of tiny things for the cross-chain tutorial. I can update the PR if you don't want them all, or feel free to cherry-pick (each is a separate commit).
1. Change the explorer link to Goerli (which is where the transaction will be), just so the user doesn't get confused
2. Add a comment to save the address of the deployed contract just to be sure the user doesn't close the terminal at this point and lose it (since it's the end of a section).
3. Add `@types/node` package to avoid some editor warnings.
> Cross chain tutorial small tweaks

- docs/dev/building-on-zksync/contracts/contract-deployment.md
- The grammar was off where punctuation matters.
- Programming languages differentiate between cases in naming conventions. `CREATE` was changed to `create()`.
- Extended a subheading for clarity; etc.
> Updated contract-deployment.md for clarity

- docs/dev/building-on-zksync/contracts/differences-with-ethereum.md
-> Added a few clarifying words to avoid confusion in future.
> Clarifying `EXTCODECOPY` entry

- docs/dev/developer-guides/aa.md
- docs/dev/tutorials/custom-aa-tutorial.md
Updates references and links, pointing to the updated function `incrementMinNonceIfEquals` from the previously mentioned `incrementNonceIfEquals`. As per the [INonceHolder interface](https://github.com/matter-labs/v2-testnet-contracts/blob/b8449bf9c819098cc8bfee0549ff5094456be51d/l2/system-contracts/interfaces/INonceHolder.sol#L13) and usage indicated in the AA tutorial [here](https://github.com/matter-labs/custom-aa-tutorial/blob/a56712817e9b7be617d7086b85f2a96c423437e0/contracts/TwoUserMultisig.sol#LL59C41-L59C66). 
Specifically, this PR includes the following updates:
- In `docs/dev/developer-guides/aa.md`, the reference to `incrementNonceIfEquals` has been updated to `incrementMinNonceIfEquals`.
- A link reference in `docs/dev/developer-guides/aa.md` previously pointing to …
> chore: Update references from `incrementNonceIfEquals` to `incrementMinNonceIfEquals`

- docs/dev/tutorials/api3-usd-paymaster-tutorial.md
- docs/dev/tutorials/custom-paymaster-tutorial.md
- docs/reference/concepts/transactions/fee-model.md
**Changes introduced in this PR:**
- Removes the "Refunds are not supported yet." comment and warning.
> chore: remove misleading refund comment

- docs/dev/building-on-zksync/hello-world.md
- docs/dev/tutorials/aa-daily-spend-limit.md
- docs/dev/tutorials/api3-usd-paymaster-tutorial.md
- docs/dev/tutorials/custom-aa-tutorial.md
- docs/dev/tutorials/custom-paymaster-tutorial.md
Add message of tutorials available on Atlas
It simplifies the process of deploying contracts to Era
In Preview page 👇
I'm running into issues with my metamask to run the scripts on Atlas as it crashes after the first transaction 🫤
> adds Atlas to tutorials

- docs/tools/testing/era-test-node.md
* Adds --locked flag to cargo install command for era-test-node which asserts installation from lock file.
* Build would fail when running `cargo install --git https://github.com/matter-labs/era-test-node.git`
```bash
Compiling sketches-ddsketch v0.2.1
error[E0631]: type mismatch in function arguments
--> /Users/dennis/.cargo/git/checkouts/zksync-era-657998444dcd9ed9/e575ec1/core/lib/types/src/aggregated_operations.rs:82:52
|
82  |                 Token::Array(proof.into_iter().map(Token::Uint).collect()),
|                                                --- ^^^^^^^^^^^
|                                                |   |
|                                                |   expected due to this
|                                                |   found signature defined here
| …
```
> fix: cargo install command to add lock flag

- docs/tools/testing/era-test-node.md
* Update `era_test_node run` output
* To match the output from the latest version of the in-memory node
> Update "era_test_node run" output to match latest version

- docs/api/api.md
Added a note on rate limiting the https and websocket API
We introduced a permissive rate limiting on websocket. http api is limited on cloudflare side
* Please have a look at the wording and whether we should add more details
> Add a warning on rate limiting

- docs/.vuepress/sidebar/en.ts
- docs/tools/hardhat/getting-started.md
- docs/tools/hardhat/hardhat-zksync-verify-vyper.md
- docs/tools/hardhat/plugins.md
* Renamed hardhat-zksync-vyper-verify to hardhat-zksync-verfiy-vyper
* Added verification context warning for the verify-vyper plugin
* Added alpha release warning for the verify-vyper plugin
* Incompatibility between plugin's name and its commands
* A feature of the zkvyper compiler to produce different contract bytecode depending of project's contracts context
> feat: add vyper verification warnings, rename plugin

- docs/tools/testing/dockerized-testing.md
* Changes link to monorepo tutorials example for Dockerized setup
* Old link was pointing to unmaintained repo.
> Point to Tutorials Repo for Dockerized Set Up

- docs/dev/how-to/verify-contracts.md
Step "1. Project setup" - aligned list style to numbers (previously both bullet list and numbers were present)
Step "5. Deploy the Greeter contract" - replaced instruction to rename the file to more obvious one from[ "Hello world" tutorial](https://era.zksync.io/docs/dev/building-on-zksync/hello-world.html#initialize-the-project)
Step "9. UI block explorer alternative" - fixed with correct link https://explorer.zksync.io/contracts/verify to "Smart Contract Verification" page
All the added fixes based on the [feedback Notion doc ](https://www.notion.so/matterlabs/Verify-Contracts-with-Hardhat-tutorial-QA-feedback-3022dfd2915840d3a95e5b5f43459633)
> qa: feedback session changes for Verify Contracts with Hardhat tutorial

- docs/dev/tutorials/aa-daily-spend-limit.md
Step "Perform ETH transfer" - fixed incorrect "0.0049" amount to correct "0.00049" 
Step "Credits" - removed incorrect external "GitCoin bounty" link
* All the added fixes based on the [Daily spending limit account - QA feedback Notion doc](https://www.notion.so/matterlabs/Daily-spending-limit-account-QA-feedback-5decf66447e240ec8a0f4ef98c901428)
> qa: feedback session changes for Daily spending limit account tutorial

- docs/dev/tutorials/custom-paymaster-tutorial.md
Added "Select "Hardhat+Solidity" option in the "Project template to use" choice" step description for step "2. Initiate a new project by running the command:"
* All the added fixes based on the [Building a custom paymaster - QA feedback](https://www.notion.so/matterlabs/Building-a-custom-paymaster-QA-feedback-08ea3273d2624b76a0bb98145cf11ec2)
> qa: feedback session changes for Building a custom paymaster tutorial

- docs/dev/how-to/transfer-token-l2.md
Added a tip to run `ts-node transfer-l2.ts` instead of `yarn ts-node transfer-l2.ts`
* All the added fixes based on the ["Transfer a token on L2" tutorial QA feedback Notion doc](https://www.notion.so/matterlabs/Transfer-a-token-on-L2-tutorial-QA-feedback-93300817e0c64dff859b00661394717d)
> qa: feedback session changes for Transfer a token on L2 tutorial

- docs/reference/architecture/differences-with-ethereum.md
Using `RETURN` or `STOP` in assembly block in the constructor will left the immutable variables uninitialized.
> Update doc to include STOP and modify the comment in RETURN example

- docs/dev/community-tutorials/redstone-marketplace-tutorial.md
* Fixes cd command to go one level lower
* Adds link to tutorial repo in text 
* cd was leading to higher level readme only
> fix: redstone tutorial missing links

- docs/dev/building-on-zksync/hello-world.md
* Installation command to install the `zksync-cli` globally using the `yarn` package manager
* The command mentioned in [docs](https://era.zksync.io/docs/dev/building-on-zksync/hello-world.html#initialize-the-project) was `yarn add global zksync-cli@latest` which is not the correct way to install packages globally, it installs the `zksync-cli` as a dependency local to the current project which essentially invalidates using the command `zksync-cli` as it is not installed globally.
The fix is to simply use the correct command `yarn global add zksync-cli@latest`.
> fix: yarn command for global installation of zksync-cli

- docs/dev/building-on-zksync/hello-world.md
- docs/reference/concepts/account-abstraction.md
* Updates documentation in AA section to remove mention of `aa-signature-checker` 
* This lib will be deprecated in favour of `@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol`
> chore: removes aa-signature-checker in favour of @openzeppelin lib

- docs/dev/building-on-zksync/hello-world.md
- docs/dev/community-tutorials/zksync-cli-quickstart.md
- docs/dev/how-to/verify-contracts.md
- docs/dev/tutorials/aa-daily-spend-limit.md
- docs/dev/tutorials/api3-usd-paymaster-tutorial.md
- docs/dev/tutorials/cross-chain-tutorial.md
- docs/dev/tutorials/custom-aa-tutorial.md
- docs/dev/tutorials/custom-paymaster-tutorial.md
- docs/reference/concepts/bridging-asset.md
- docs/tools/hardhat/getting-started.md
- docs/tools/hardhat/hardhat-zksync-vyper.md
- docs/tools/zksync-cli/README.md
* Update zkSync CLI documentation according to the command restructure from https://github.com/matter-labs/zksync-cli/pull/64
* Make docs up-to-date with latest version of zkSync CLI
* Should be merged with [zkSync CLI PR](https://github.com/matter-labs/zksync-cli/pull/64)
> fix: zksync cli commands restructure

- docs/dev/how-to/send-transaction-l1-l2.md
- Updated the `/tools/hardhat/getting-started.md` to fix the link of [IZSync](https://era.zksync.io/docs/dev/how-to/send-transaction-l1-l2.html#step-by-step) to the era contracts.
- Because it was linking into a bad request
* All good
> fix: correct link for IZkSync Interface link

- firebase.json
- Google search for "the graph zksync" showed up this link https://era.zksync.io/docs/dev/community-tutorials/the-graph-tutorial.html which is 404; 
- fix it by redirecting it to here https://github.com/zkSync-Community-Hub/tutorials/blob/main/tutorials/the-graph/TUTORIAL.md
- broken link: https://era.zksync.io/docs/dev/community-tutorials/the-graph-tutorial.html
> fix: firebase source to redirect at github link tutorial

- docs/tools/testing/README.md
- docs/tools/zksync-cli/README.md
* Added info about Block Explorer for zkSync CLI
* To let users know that they can easily start Block Explorer locally with zkSync CLI
> fix: add info block cli block explorer

- docs/assets/data/devtools.json
* Remove duplicate Rust SDK from Dev Tools
* Causing confusion. Kept the one that links to the Docs and not directly to the GitHub repo.
Only 1 Rust SDK in the list:
> chore: remove duplicate rust sdk from dev tools

- CODEOWNERS
* Add `devxp` team as additional owners of repo
* The `product` team does not encompass the full team responsible for a lot of content in these docs
> chore: add devxp team as additional owners of repo

- docs/dev/tutorials/custom-paymaster-tutorial.md
* Removed zkSync Portal mention - replaced it by Bridges https://zksync.io/explore#bridges page
* We have obsolete zkSync Portal mention  in a doc
> chore: remove zkSync Portal mention

- docs/assets/data/devtools.json
* updated Safe URL to https://app.safe.global/welcome since recently zkSync Era was officially added to app.safe.global and Protofire finished its support
* Outdated Protofire link
> chore: update Safe URL

- docs/api/js/zksync2-js/examples/create.md
- docs/api/js/zksync2-js/examples/create2.md
- docs/api/js/zksync2-js/examples/custom-paymaster/deploy-account.md
- docs/api/js/zksync2-js/examples/custom-paymaster/deploy-token.md
* Improve examples related to account and contract deployment in `zksync2-js`.
* There is no create separate `ethers.Contract` after the account/contract is deployed with `ContractFactory.deploy`. Account/contract that is returned by `ContractFactory.deploy` can be used as well.
> fix: improve examples releated to deployment in `zksync2-js`

- docs/api/api.md
- docs/api/java/providers.md
- docs/api/js/providers.md
- removed zks_getTokenPrice docs
- removed getTokenPrice SDKs methods docs
- zks_getTokenPrice will no longer be supported, it replaced with explorer APIs
> fix: remove zks_getTokenPrice docs

- docs/reference/troubleshooting/docs-contribution/docs.md
* Removed depredated Telegram support group link mentioned in "Contribute to documents" doc - the group has been deprecated earlier this year
> chore: remove depredated Telegram support group link

- docs/dev/how-to/send-message-l2-l1.md
* Markdown formatting for nested bullets in the parameter details sections for [Send an L2 to L1 message docs](https://era.zksync.io/docs/dev/how-to/send-message-l2-l1.html#prove-the-result)
* A bit easier and clearer to read
> chore: format nested bullets

- cspell-zksync.txt
- cspell.json
- docs/dev/building-on-zksync/hello-world.md
- docs/dev/how-to/send-message-l2-l1.md
- docs/dev/how-to/verify-contracts.md
- docs/dev/tutorials/aa-daily-spend-limit.md
- docs/dev/tutorials/api3-usd-paymaster-tutorial.md
- docs/dev/tutorials/cross-chain-tutorial.md
- docs/dev/tutorials/custom-aa-tutorial.md
- docs/dev/tutorials/custom-paymaster-tutorial.md
- docs/reference/concepts/bridging-asset.md
- docs/tools/hardhat/getting-started.md
- docs/tools/zksync-cli/README.md
* `zksync-cli create project` command renamed to `zksync-cli create`
* Always use `npx` when showcasing zksync-cli commands
* Change command according to the update
* It seems a lot of people still install it globally, this will make them not receive latest updates automatically.
* Related zksync-cli PR - https://github.com/matter-labs/zksync-cli/pull/76
> fix: update cli docs according to new cli update

- docs/api/js/zksync2-js/utils.md
* Add `l2Value` parameter to `utils.estimateCustomBridgeDepositL2Gas` function.
* To follow the changed to latest SDK version.
> fix(js): add missing paramter to `utils.estimateCustomBridgeDepositL2Gas`

- docs/reference/troubleshooting/audit-bug-bounty.md
* Fix the internal audit date
* The month is `14`, which cannot be. I'm assuming the month and day are swapped.
> fix: update internal audit date

- docs/dev/tutorials/custom-paymaster-tutorial.md
Fixes for custom paymaster tutorial:
1. Simplify the tutorial by removing unnecessary instructions, like remove `Greeter.sol` and corresponding deployment scripts. It doesn't hurt to have them in the folder, but such instructions can distract users from the main topic of the tutorial.
2. Incorporate recent template changes into the tutorial: slightly rewrite deploy and interact scripts, update examples output etc.
We need to keep our tutorials up to date.
Example of the updated code snippet:
> fix: custom paymaster tutorial

- docs/reference/concepts/bridging-asset.md
* Remove mention of token form
* Token form is deprecated
> fix: remove token form mention

- docs/dev/how-to/send-transaction-l1-l2.md
New line for using zksync-cli is added.
For the L1-L2 tutorial a new information is added. How user can run local-node using zksync-cli tool. 
Added 2 option for remote run (NPX) and also possibility to run thought local installation.
- for NPX
- for NPM (local package install)
[Updated tutorial L1-L2 transaction.](https://era.zksync.io/docs/dev/how-to/send-transaction-l1-l2.html)
Provide easier way for user to run local-node.
Motivate to use zksync-cli project.
Provide visibility of simple and quick to use from developer side.
> [QA] Add zksync-cli instructions for l1-l2 tutorial

- docs/api/api.md
* Update description of `hash` parameter in `zks_getBytecodeByHash` RPC endpoint.
* Address is 20 bytes long, hash is 32 bytes. Previous version of description was:  'Hass address as string'  which did not make any sense.
> fix(api): make clearer description of `hash` parameter in `zks_getBytecodeByHash` rpc method

- docs/tools/zksync-cli/README.md
* Change `--l2-rpc` to `--rpc`
* zksync-cli was updated to provide easier and more consistent option names
> fix: update zksync-cli rpc option

- docs/api/js/zksync2-js/examples/withdraw.md
- docs/api/js/zksync2-js/providers.md
* Document `Provider.getBytecodeByHash` and `Provider.getRawBlockTransactions`.
* Fix bug in withdraw example.
* To align with latest SDK version.
* Better UX.
Both methods are covered with test:
- [Provder.getBytecodeByHash](https://github.com/zksync-sdk/zksync2-js/blob/main/tests/integration/provider.test.ts#L108).
- [Provider.getRawBlockTransactions](https://github.com/zksync-sdk/zksync2-js/blob/main/tests/integration/provider.test.ts#L116).
> fix(js-sdk): document `Provider.getBytecodeByHash` and `Provider.getRawBlockTransactions`

- docs/.vuepress/sidebar/en.ts
- docs/tools/hardhat/getting-started.md
- docs/tools/hardhat/hardhat-zksync-chai-matchers.md
- docs/tools/hardhat/hardhat-zksync-deploy.md
- docs/tools/hardhat/hardhat-zksync-ethers.md
- docs/tools/hardhat/hardhat-zksync-upgradable.md
- docs/tools/hardhat/migrating-to-zksync.md
- docs/tools/hardhat/plugins.md
- docs/tools/testing/dockerized-testing.md
- docs/tools/testing/era-test-node.md
* Migration from zksync2-js to zksync-ethers
* hardhat-zksync-zksyn2js plugin change name to hardhat-zksync-ethers
* Examples update to support ethers v6
> chore(plugins): migration from zksync2-js to zksync-ethers

- .github/workflows/checks.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/release.yml
update Node version used in build CI for it to pass, as v16 is now unsupported
> ci: update NPM versions for deploy-prod to use node LTS

- docs/dev/tutorials/aa-daily-spend-limit.md
- solidity version required 0.8.20, but in the tutorial hardhat file we have 0.8.17 mentioned 
- in the deployFactoryAccount.ts file there’s a name for private key variable DEPLOYER_PRIVATE_KEY  but in the .env file from the downloaded template we have WALLET_PRIVATE_KEY= 
- 
> Spend Limit tutorial: new solidity version а or hardhat and env var for wallet private key

- docs/.vuepress/sidebar/en.ts
- docs/assets/data/devtools.json
- docs/dev/README.md
- docs/dev/tutorials/README.md
- docs/dev/tutorials/api3-usd-paymaster-tutorial.md
* Hide the API3 paymaster tutorial
* Remove API3 from Oracles in Dev Tools
* API3 has removed support for our network and the tutorial no longer works
> docs: update api3-usd-paymaster-tutorial.md

- docs/api/go/paymaster-utils.md
- docs/api/js/paymaster-utils.md
- docs/api/js/zksync2-js/paymaster-utils.md
- docs/api/python/paymaster-utils.md
- docs/dev/how-to/estimate-gas.md
- docs/dev/how-to/send-transaction-l1-l2.md
- docs/reference/concepts/bridging-asset.md
- docs/reference/concepts/fee-model.md
- updated `era-contracts` and `era-system-contracts` links to reflect contract repo merge changes:
- https://github.com/matter-labs/era-contracts/pull/98
- some of the links in the docs were broken due to the system contract repo merge
> docs: updated era-contracts links

- docs/zk-stack/README.md
* zkstack landing page links
* they're 404
> fix: zkstack landing links

- docs/build/sdks/java/providers.md
* Fix typo
* `zksAccountBalances` was mispelled
* Addresses https://github.com/matter-labs/zksync-web-era-docs/pull/804 from @pekkadt04
> fix: typo in zksAccountBalances for java sdk

- docs/build/developer-reference/differences-with-ethereum.md
- docs/build/developer-reference/fee-model.md
- docs/build/developer-reference/l1-l2-interop.md
- docs/build/sdks/go/accounts.md
- docs/build/sdks/go/features.md
- docs/build/support/faq.md
- docs/build/tooling/hardhat/getting-started.md
- docs/build/tooling/hardhat/hardhat-zksync-deploy.md
- docs/build/tooling/node-providers.md
- docs/build/tooling/zksync-cli/examples/contract-interaction.md
- docs/build/tutorials/dapp-development/gated-nft-paymaster-tutorial.md
- docs/build/tutorials/smart-contract-development/account-abstraction/daily-spend-limit.md
- docs/zk-stack/concepts/transaction-lifecycle.md
* Fix typos across various docs
* Updated the URL for DRPC
* Easier readability
* Corrected the URL for DRPC to direct users to the specific zksync-related endpoints
* Addresses https://github.com/matter-labs/zksync-web-era-docs/pull/809 from @tudorpintea999
* Addresses https://github.com/matter-labs/zksync-web-era-docs/pull/816 from @Dushyantgoswami
* Addresses https://github.com/matter-labs/zksync-web-era-docs/pull/818 from @pandabadger 
* Addresses https://github.com/matter-labs/zksync-web-era-docs/pull/819 from @vehorny
> fix: typos across various docs

- README.md
Came across dead link in README file : https://github.com/matter-labs/zksync-wallet/blob/master/LICENSE-MIT 
Updated them to the license files from that repository, MIT and APACHE
Have a nice evening
> chore: updated link in README

- cspell-zksync.txt
- docs/build/quick-start/best-practices.md
- docs/build/sdks/rust/getting-started.md
- docs/build/sdks/swift/accounts.md
- docs/build/tooling/hardhat/hardhat-zksync-ethers.md
- docs/build/tooling/hardhat/other-plugins.md
- docs/build/tutorials/smart-contract-development/account-abstraction/custom-aa-tutorial.md
- docs/build/tutorials/tooling-guides/dia.md
- docs/zk-stack/components/prover/boojum-function-check-if-satisfied.md
- docs/zk-stack/components/prover/circuits/sha256-round-function.md
- docs/zk-stack/components/zkEVM/precompiles.md
* Fix typos in markdown files
* Remove typos from cspell file
* For better user experience
* To ensure they don't continue in the future
> fix: several typos

- .github/workflows/deploy-preview.yml
* Allow upstream forks to deploy preview
* So that we can have higher confidence in changes coming from forks
* Only users with `Write` access to this repo are allowed to manually trigger a GitHub Action. And if they already have `Write` access, then they can just make a branch directly and not from a fork. The expectation is that reviewers of incoming PRs need to review code before approving the CI builds.
> feat: allow manual preview creation from forks

- .github/workflows/deploy-preview.yml
* Allow users with `Write` access to manually trigger a deploy preview for upstream forks
* So that we can have higher confidence in changes coming from forks
* Secrets should not be shared with upstream PRs and we require secrets for firebase deploys
> fix: build preview for upstream pull requests

- docs/zk-stack/components/shared-bridges.md
* I have added a link to the corresponding page for the reader's convenience 
* Ease of use
in the previous version the user had to search
> Add link to corresponding page

- docs/zk-stack/running-a-hyperchain/locally.md
* Fixed export statement for path being both on 1 line
* If not people might run command wrong
> fix: fixing export statement being in 1 line

- docs/zk-stack/running-a-hyperchain/locally.md
* Update minimum prover GPU RAM requirements from 16Gb -> 6Gb
* Because @robik75 is kick ass and [lowered](https://github.com/matter-labs/era-shivini/pull/27) GPU RAM requirements from 16Gb -> 6Gb
> chore(prover): update min prover gpu ram from 16gb to 6gb

- docs/build/tutorials/how-to/send-transaction-l1-l2.md
* removed `npm` codeblock tab for zksync-cli - just `npx` left (fix requested by @JackHamer09)
> fix: removing npm tab for zksync-cli

- docs/.vuepress/sidebar/en.ts
- docs/build/tutorials/tooling-guides/web3js.md
* Add tooling guide for zkSync plugin for Web3.js
> Web3.js Plugin Tooling Guide

- docs/zk-stack/running-a-hyperchain/locally.md
updating the portal command.
npm run hyperchain:migrate is not working anymore.
> Update dapp portal command

- docs/zk-stack/concepts/blocks.md
We were not mentioning in the docs that the empty block contains a transfer event
* Small addition of information
* To provide more accurate info so people are not confused when they see an event in an empty block
> Update blocks.md with transfer event information

- docs/build/tutorials/smart-contract-development/account-abstraction/custom-aa-tutorial.md
- docs/build/tutorials/smart-contract-development/account-abstraction/daily-spend-limit.md
Fixed the word `mae` to the correctly spelled `make`
cuz spelling gud
see spelling
> fix: the word "make" was spelled incorrect

- cspell-zksync.txt
- docs/build/developer-reference/contract-deployment.md
* Added cyfrin updraft security curriculum
* It is the most extensive, up to date, and thorough, security and auditing curriculum ever created
> feat: add Cyfrin Updraft security curriculum for security education

- docs/build/tooling/oracles.md
* The current link to the Pyth docs is broken, I updated it to https://docs.pyth.network/price-feeds
> Fixing broken link to Pyth docs

- docs/build/tooling/block-explorer/block-explorer-api.md
- docs/build/tooling/block-explorer/getting-started.md
* The documentation for the explorer was using a dead link for the testnet api link. This PR changes that link to one that seems to be the right one.
* It is confusing having a dead link on the testnet api. My first impression was that the public api was not available por testnet. Which was weird. I found the real link inspecting the behavior of the production version of the testnet explorer.
Old link:
New link:
> Using correct link for testnet sepolia api docs.

- docs/build/tooling/hardhat/hardhat-zksync-deploy.md
- docs/build/tooling/hardhat/hardhat-zksync-upgradable.md
- docs/build/tutorials/smart-contract-development/account-abstraction/custom-aa-tutorial.md
- docs/build/tutorials/smart-contract-development/account-abstraction/daily-spend-limit.md
* Set deployment type per each deployment and not per per deployer object
* User can change deployment type per each deployment and don't need to set new deployment type in deployer object or create a new deployer to use a new deployment type.
> chore: use deployment type in the deploy function

- docs/build/tooling/hardhat/hardhat-zksync-node.md
* Add `--tag` param to the hardhat-zksync-node command list
*  Fill the gap in our docs for hardhat-zksync-node where we don't clarify that `--tag` exists so user can specify era test node release.
> chore: add --tag param to the hardhat-zksync-node command list
